### ISSUE TITLE
Exits without output on Apple Silicon

### ISSUE THREAD

**Issue by tomjn** [configuredco/haulable#3]
I fired up Laravel zero and created the base example CLI app, then tried to use Haulage to package it for apple silicon. I wanted to see how large the result would be, but found that after `chmod +x`'ing the output it wouldn't execute and is returning a bad error code of `1` and a newline, but nothing else

**Comment by joecampo** [comment]
Hey there, thanks so much for reporting! For which PHP version? This package is incredibly simple as it just concatenates the `phar` with PHP Micro CLI's self-extracting wrapper `.sfx`.

There are two things that I think this could be:

* I have the wrong `.sfx` wrapper assigned to that specific PHP version
* Something else is wonky with the PHP Micro CLI sfx build

More than likely I'd imagine it is something I goofed up 😅. Unfortunately, I don't have access to an Apple Silicon machine at the moment to test. If you're interested in helping, I'd be more than grateful. 

If you'd be able to help test: From the latest build here: https://github.com/dixyes/lwmbs/actions/runs/5207423135

* From the `Artifacts` section download the applicable `micro-cli` zipped artifact for your PHP version
* The zip file will contain the `micro-cli.sfx` file
* Take your `phar` that you built and concatenate them together `cat micro-cli.sfx demo.phar > demo.phar`
* `chmod +x` the outputted phar, and it *should run*.
