### ISSUE TITLE
Support Linux aarch64

### ISSUE THREAD

**Issue by filipac** [configuredco/haulable#4]
Is there a way you can support building for aarch64 - linux? There is a sfx file for that architecture, I could make a PR but I do not have access to https://haulable.configured.co/ to upload the binary there.

https://dl.zhamao.xin/static-php-cli/

**Comment by giovanne-oliveira** [comment]
@filipac I'm planning to fire up a new server to store those files and open a PR to change that URL. Maybe a Cloudflare R2 endpoint. The project seems to be abandoned by the creator.

**Comment by joecampo** [comment]
@giovanne-oliveira Not abandoned. I've just been busy this week. I'll tackle this tomorrow.

**Comment by joecampo** [comment]
@giovanne-oliveira @filipac This is done in [0.4.0](https://github.com/configuredco/haulable/releases/tag/v0.4.0)

Here's a screen shot from a test CLI app running on a Raspberry Pi (without PHP installed)

![image](https://github.com/configuredco/haulable/assets/3619398/2d8510c0-cb36-427b-9233-ac47b7997a5e)
